Add basic policy evaluation to crates download
seedwing-io/seedwing-proxy pull request #20
Opened 2023-02-02 01:52 UTC by lkatalin

I tested pass/fail policy cases with crates, but not more nuanced sigstore-based policies yet.

2023-02-02 14:33 UTC, jcrossley3 reviewed
Nice!

2023-02-02 14:33 UTC, jcrossley3 commented on src/repositories/crates/api/v1/mod.rs
> +                            response.append_header((header::CONTENT_DISPOSITION, disposition));
I'm not sure about this. Are those two headers enough? Are they what the client expects? In the Maven handler, I just relay all the headers and use the upstream status. If we think that's correct, maybe we should factor it out to a common lib. Thoughts?

```suggestion
                        let mut response = HttpResponseBuilder::new(upstream.status());
                        for header in upstream.headers().iter() {
                            response.insert_header(header);
                        }
                        response.body(payload)
```

2023-02-02 14:33 UTC, jcrossley3 commented on src/repositories/crates/api/v1/mod.rs
> +                            return response.body(payload);
Personally, I prefer omitting `return` unless the code is clearer using an "early exit".

```suggestion
                            response.body(payload)
```

2023-02-02 14:33 UTC, jcrossley3 commented on src/repositories/crates/api/v1/mod.rs
> +                            return response;
```suggestion
                            response
```

2023-02-02 14:33 UTC, jcrossley3 commented on src/repositories/crates/api/v1/mod.rs
> +                            return e.into();
```suggestion
                            e.into()
```

2023-02-02 14:33 UTC, jcrossley3 commented on src/repositories/crates/git.rs
> +use super::CratesConfig;
Good :)

2023-02-02 16:40 UTC, lkatalin commented on src/repositories/crates/api/v1/mod.rs
> +                            response.append_header((header::CONTENT_DISPOSITION, disposition));
@jcrossley3 I had actually just moved the existing code into that block if the policy eval succeeds, but I agree it could use a double check and also that we should implement common libraries where possible (that's going to be one of the next things I want to look at more generally). I like your suggestion and can update.

2023-02-02 17:06 UTC, lkatalin commented on src/repositories/crates/api/v1/mod.rs
> +                            return response.body(payload);
After looking at this for a bit, it is an "early exit" with the way the code is structured currently. I've been reworking it to look more like the maven `proxy()` function, but in this case I think it may be making the logic harder to follow as we're returning many types of errors and have so many nested matches.

2023-02-02 17:07 UTC, lkatalin commented on src/repositories/crates/api/v1/mod.rs
> +                            return response.body(payload);
All this to say, still working on it, as I'd like the two to look more similar rather than less.

2023-02-03 17:52 UTC, lkatalin commented
@jcrossley3 I reworked this a bit to use `?` instead of an unwieldy amount of `match` statements.

2023-02-03 18:20 UTC, jcrossley3 requested changes
I dig the new error handling. Nice work!

2023-02-03 18:20 UTC, jcrossley3 commented on src/repositories/crates/api/v1/mod.rs
> +            let uuids = search(digest.clone()).await;
We don't need this anymore, right? Policy engine will do this.

2023-02-03 20:51 UTC, lkatalin commented on src/repositories/crates/api/v1/mod.rs
> +            let uuids = search(digest.clone()).await;
Good catch, that was left in from earlier. Fixed.

2023-02-06 17:43 UTC, lkatalin commented
@jcrossley3 WDYT, is this one good to merge?

2023-02-06 18:29 UTC, jcrossley3 approved these changes

2023-02-06 19:53 UTC, merged